import "dotenv/config";

const ENV = process.env;
const SUPPORTED_ASSETS = (ENV.MODEL_SUPPORTED_ASSETS || "btc,eth,sol,xrp")
  .split(",")
  .map((asset) => asset.trim())
  .filter((asset) => asset.length > 0);
const SUPPORTED_WINDOWS = (ENV.MODEL_SUPPORTED_WINDOWS || "5m,15m")
  .split(",")
  .map((window) => window.trim())
  .filter((window) => window.length > 0);

const config = {
  RESPONSE_CONTENT_TYPE: ENV.RESPONSE_CONTENT_TYPE || "application/json",
  DEFAULT_PORT: Number(ENV.PORT || 3000),
  SERVICE_NAME: ENV.SERVICE_NAME || "@sha3/polymarket-model",
  MODEL_STATE_PATH: ENV.MODEL_STATE_PATH || "",
  MODEL_STATE_DIR: ENV.MODEL_STATE_DIR || ENV.MODEL_STATE_PATH || "./var/model-state",
  MODEL_STATE_TMP_DIR: ENV.MODEL_STATE_TMP_DIR || "",
  SNAPSHOT_COLLECTOR_URL: ENV.SNAPSHOT_COLLECTOR_URL || "http://127.0.0.1:3000",
  SNAPSHOT_COLLECTOR_CACHE_TTL_MS: Number(ENV.SNAPSHOT_COLLECTOR_CACHE_TTL_MS || 2_000),
  SNAPSHOT_COLLECTOR_PAGE_LIMIT: Number(ENV.SNAPSHOT_COLLECTOR_PAGE_LIMIT || 5_000),
  LIVE_SNAPSHOT_INTERVAL_MS: Number(ENV.LIVE_SNAPSHOT_INTERVAL_MS || 500),
  LIVE_SNAPSHOT_BUFFER_LIMIT: Number(ENV.LIVE_SNAPSHOT_BUFFER_LIMIT || 1_024),
  MODEL_SUPPORTED_ASSETS: SUPPORTED_ASSETS,
  MODEL_SUPPORTED_WINDOWS: SUPPORTED_WINDOWS,
  MODEL_HISTORY_LOOKBACK_HOURS: Number(ENV.MODEL_HISTORY_LOOKBACK_HOURS || 336),
  MODEL_TRAINING_INTERVAL_MS: Number(ENV.MODEL_TRAINING_INTERVAL_MS || 86_400_000),
  MODEL_DECISION_INTERVAL_MS: Number(ENV.MODEL_DECISION_INTERVAL_MS || 30_000),
  MODEL_PREDICTION_HORIZON_MS: Number(ENV.MODEL_PREDICTION_HORIZON_MS || 30_000),
  MODEL_EMBARGO_MS: Number(ENV.MODEL_EMBARGO_MS || 60_000),
  MODEL_CHAINLINK_STALE_MS: Number(ENV.MODEL_CHAINLINK_STALE_MS || 60_000),
  MODEL_POLYMARKET_STALE_MS: Number(ENV.MODEL_POLYMARKET_STALE_MS || 15_000),
  MODEL_MIN_SAMPLE_COUNT: Number(ENV.MODEL_MIN_SAMPLE_COUNT || 12),
  MODEL_ARTIFACT_RETENTION: Number(ENV.MODEL_ARTIFACT_RETENTION || 1),
  MODEL_RESTORE_ON_START: (ENV.MODEL_RESTORE_ON_START || "true") === "true",
  MODEL_LOG_TRAINING_PROGRESS: (ENV.MODEL_LOG_TRAINING_PROGRESS || "true") === "true",
  MODEL_FEE_CACHE_TTL_MS: Number(ENV.MODEL_FEE_CACHE_TTL_MS || 30_000),
  MODEL_MAX_SPREAD: Number(ENV.MODEL_MAX_SPREAD || 0.1),
  MODEL_SPREAD_BUFFER_KAPPA: Number(ENV.MODEL_SPREAD_BUFFER_KAPPA || 0.75),
  MODEL_FUSION_ALPHA_0: Number(ENV.MODEL_FUSION_ALPHA_0 || 0.2),
  MODEL_FUSION_ALPHA_1: Number(ENV.MODEL_FUSION_ALPHA_1 || 0.6),
  MODEL_VETO_DOWN_THRESHOLD: Number(ENV.MODEL_VETO_DOWN_THRESHOLD || 0.7),
  MODEL_ENABLE_CLOB_ONLY_FALLBACK: (ENV.MODEL_ENABLE_CLOB_ONLY_FALLBACK || "true") === "true",
  MODEL_TRAIN_WINDOW_DAYS: Number(ENV.MODEL_TRAIN_WINDOW_DAYS || 14),
  MODEL_VALIDATION_WINDOW_DAYS: Number(ENV.MODEL_VALIDATION_WINDOW_DAYS || 2),
  MODEL_CLASSIFICATION_WEIGHT: Number(ENV.MODEL_CLASSIFICATION_WEIGHT || 0.5),
  MODEL_TF_EPOCHS: Number(ENV.MODEL_TF_EPOCHS || 25),
  MODEL_TF_BATCH_SIZE: Number(ENV.MODEL_TF_BATCH_SIZE || 32),
  MODEL_TF_LEARNING_RATE: Number(ENV.MODEL_TF_LEARNING_RATE || 0.01),
  MODEL_TF_EARLY_STOPPING_PATIENCE: Number(ENV.MODEL_TF_EARLY_STOPPING_PATIENCE || 3),
  MODEL_EXECUTION_SIZE: Number(ENV.MODEL_EXECUTION_SIZE || 25),
  TENSORFLOW_API_URL: ENV.TENSORFLOW_API_URL || "http://127.0.0.1:3100",
  TENSORFLOW_API_AUTH_TOKEN: ENV.TENSORFLOW_API_AUTH_TOKEN || "",
  TENSORFLOW_API_REQUEST_TIMEOUT_MS: Number(ENV.TENSORFLOW_API_REQUEST_TIMEOUT_MS || 30_000),
  TENSORFLOW_API_TRAIN_POLL_INTERVAL_MS: Number(ENV.TENSORFLOW_API_TRAIN_POLL_INTERVAL_MS || 2_000),
  TENSORFLOW_API_TRAIN_TIMEOUT_MS: Number(ENV.TENSORFLOW_API_TRAIN_TIMEOUT_MS || 1_200_000),
} as const;

export default config;
