import "dotenv/config";

const ENV = process.env;
const SUPPORTED_ASSETS = (ENV.MODEL_SUPPORTED_ASSETS || "btc,eth,sol,xrp")
  .split(",")
  .map((asset) => asset.trim())
  .filter((asset) => asset.length > 0);

const config = {
  RESPONSE_CONTENT_TYPE: ENV.RESPONSE_CONTENT_TYPE || "application/json",
  DEFAULT_PORT: Number(ENV.PORT || 3200),
  SERVICE_NAME: ENV.SERVICE_NAME || "@sha3/polymarket-model",
  MODEL_STATE_PATH: ENV.MODEL_STATE_PATH || "",
  MODEL_STATE_DIR: ENV.MODEL_STATE_DIR || ENV.MODEL_STATE_PATH || "./var/model-state",
  MODEL_STATE_TMP_DIR: ENV.MODEL_STATE_TMP_DIR || "",
  SNAPSHOT_COLLECTOR_URL: ENV.SNAPSHOT_COLLECTOR_URL || "http://127.0.0.1:3000",
  SNAPSHOT_COLLECTOR_CACHE_TTL_MS: Number(ENV.SNAPSHOT_COLLECTOR_CACHE_TTL_MS || 2_000),
  SNAPSHOT_COLLECTOR_PAGE_LIMIT: Number(ENV.SNAPSHOT_COLLECTOR_PAGE_LIMIT || 1_000),
  SNAPSHOT_COLLECTOR_REQUEST_TIMEOUT_MS: Number(ENV.SNAPSHOT_COLLECTOR_REQUEST_TIMEOUT_MS || 30_000),
  SNAPSHOT_COLLECTOR_MAX_ATTEMPTS: Number(ENV.SNAPSHOT_COLLECTOR_MAX_ATTEMPTS || 4),
  SNAPSHOT_COLLECTOR_RETRY_BASE_DELAY_MS: Number(ENV.SNAPSHOT_COLLECTOR_RETRY_BASE_DELAY_MS || 250),
  LIVE_SNAPSHOT_INTERVAL_MS: Number(ENV.LIVE_SNAPSHOT_INTERVAL_MS || 500),
  LIVE_SNAPSHOT_BUFFER_LIMIT: Number(ENV.LIVE_SNAPSHOT_BUFFER_LIMIT || 1_024),
  MODEL_SUPPORTED_ASSETS: SUPPORTED_ASSETS,
  MODEL_PROCESS_INTERVAL_MS: Number(ENV.MODEL_PROCESS_INTERVAL_MS || 2_000),
  MODEL_BLOCK_DURATION_MS: Number(ENV.MODEL_BLOCK_DURATION_MS || 300_000),
  MODEL_PREDICTION_CONTEXT_MS: Number(ENV.MODEL_PREDICTION_CONTEXT_MS || 30_000),
  MODEL_PREDICTION_TARGET_MS: Number(ENV.MODEL_PREDICTION_TARGET_MS || 30_000),
  MODEL_PREDICTION_HORIZON_MS: Number(ENV.MODEL_PREDICTION_TARGET_MS || 30_000),
  MODEL_DECISION_INTERVAL_MS: Number(ENV.MODEL_PREDICTION_CONTEXT_MS || 30_000),
  MODEL_ROLLING_HIT_RATE_WINDOW_MS: Number(ENV.MODEL_ROLLING_HIT_RATE_WINDOW_MS || 7_200_000),
  MODEL_HIT_RATE_MIN_CONFIDENCE: Number(ENV.MODEL_HIT_RATE_MIN_CONFIDENCE || 0.7),
  MODEL_CHAINLINK_STALE_MS: Number(ENV.MODEL_CHAINLINK_STALE_MS || 60_000),
  MODEL_MIN_SAMPLE_COUNT: Number(ENV.MODEL_MIN_SAMPLE_COUNT || 4),
  MODEL_AUTOMATIC_PREDICTIONS_ENABLED: (ENV.MODEL_AUTOMATIC_PREDICTIONS_ENABLED || "true") === "true",
  MODEL_RESTORE_ON_START: (ENV.MODEL_RESTORE_ON_START || "true") === "true",
  MODEL_LOG_TRAINING_PROGRESS: (ENV.MODEL_LOG_TRAINING_PROGRESS || "true") === "true",
  MODEL_TF_EPOCHS: Number(ENV.MODEL_TF_EPOCHS || 25),
  MODEL_TF_BATCH_SIZE: Number(ENV.MODEL_TF_BATCH_SIZE || 32),
  MODEL_TF_LEARNING_RATE: Number(ENV.MODEL_TF_LEARNING_RATE || 0.01),
  TENSORFLOW_API_URL: ENV.TENSORFLOW_API_URL || "http://127.0.0.1:3100",
  TENSORFLOW_API_AUTH_TOKEN: ENV.TENSORFLOW_API_AUTH_TOKEN || "",
  TENSORFLOW_API_REQUEST_TIMEOUT_MS: Number(ENV.TENSORFLOW_API_REQUEST_TIMEOUT_MS || 30_000),
  TENSORFLOW_API_MAX_ATTEMPTS: Number(ENV.TENSORFLOW_API_MAX_ATTEMPTS || 4),
  TENSORFLOW_API_RETRY_BASE_DELAY_MS: Number(ENV.TENSORFLOW_API_RETRY_BASE_DELAY_MS || 250),
  TENSORFLOW_API_TRAIN_POLL_INTERVAL_MS: Number(ENV.TENSORFLOW_API_TRAIN_POLL_INTERVAL_MS || 2_000),
  TENSORFLOW_API_TRAIN_TIMEOUT_MS: Number(ENV.TENSORFLOW_API_TRAIN_TIMEOUT_MS || 1_200_000),
} as const;

export default config;
